sudo: false
cache: pip
language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
  - pip install . flake8 isort black
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  - flake8 ptterm

  # Check wheather the imports were sorted correctly.
  # When this fails, please run ./tools/sort-imports.sh
  - isort -c -rc ptterm setup.py examples

  - black --check ptterm setup.py examples
