sudo: false
cache: pip
language: python

matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: required
    - python: 3.6

install:
  - pip install . flake8 isort black
  - pip list

script:
  - echo "$TRAVIS_PYTHON_VERSION"
  # Setting --max-line-length 88 to set as
  # the default value of black
  - flake8 --max-line-length 88 --ignore E203,W503 ptterm
  # Check wheather the imports were sorted correctly.
  # When this fails, please run ./tools/sort-imports.sh
  # Removing -rc as is not more needed in new isort releases.
  - isort -c ptterm setup.py examples
  - black --check ptterm setup.py examples
