[tool.ruff]
target-version = "py37"
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "C",  # flake8-comprehensions
    "T",  # Print.
    "I",  # isort
    # "B",  # flake8-bugbear
    "UP",  # pyupgrade
    "RUF100",  # unused-noqa
    "Q",  # quotes
]
ignore = [
    "E501",  # Line too long, handled by black
    "C901",  # Too complex
    "E722",  # bare except.
]


[tool.ruff.per-file-ignores]


[tool.ruff.isort]
known-first-party = ["ptterm"]
known-third-party = ["prompt_toolkit"]
